package infres.ws.client;

import infres.ws.client.generated.*;
import infres.ws.soap.model.Reservation;

import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

public class WebServiceClient {
    public static void main(String[] args) {
        WebServiceClient client = new WebServiceClient();
        client.doTest();
    }

    public void doTest() {
        try {
//            RoomWebServiceImplService service = new RoomWebServiceImplService(); // Create a new instance of the service class generated by wsimport
//            RoomWebService port = service.getRoomWebServiceImplPort(); // Get a proxy for the port to the service
//
//            Room room = port.getRoom(1); // Invoke the web service method
//            System.out.println(room.toString());
//
//            ReservationWebServiceImplService service2 = new ReservationWebServiceImplService(); // Create a new instance of the service class generated by wsimport
//            ReservationWebService port2 = service2.getReservationWebServiceImplPort(); // Get a proxy for the port to the service
//
//            GregorianCalendar gregorianCalendar = new GregorianCalendar();
//            gregorianCalendar.setTime(new Date());
//            DatatypeFactory datatypeFactory = DatatypeFactory.newInstance();
//            XMLGregorianCalendar xmlGregorianCalendar = datatypeFactory.newXMLGregorianCalendar(gregorianCalendar);
//
//            RoomWebServiceImplService service3 = new RoomWebServiceImplService(); // Create a new instance of the service class generated by wsimport
//            RoomWebService port3 = service3.getRoomWebServiceImplPort(); // Get a proxy for the port to the service
//
//            List<Room> room3 = port3.getRooms(); // Invoke the web service method
//            System.out.println(room3.toString());
//
//            //Room room2 = port2.createReservation(xmlGregorianCalendar, xmlGregorianCalendar, 1, "John Doe"); // Invoke the web service method
//            //System.out.println(room2.getRoomNumber());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
